import type { Job, Application, Resume, CoverLetter, Interview, Activity, Analytics, AgentLog } from "@/types";

export const sampleJobs: Job[] = [
  {
    id: "1",
    title: "Senior Software Engineer",
    company: "Google",
    companyLogo: "https://logo.clearbit.com/google.com",
    location: "Mountain View, CA",
    type: "full-time",
    remote: "hybrid",
    salaryMin: 150000,
    salaryMax: 220000,
    salaryCurrency: "USD",
    description: "We are looking for a Senior Software Engineer to join our team.",
    requirements: ["5+ years of experience", "React", "TypeScript", "Node.js", "AWS"],
    niceToHave: ["GCP", "Kubernetes", "Machine Learning"],
    techStack: ["React", "TypeScript", "Node.js", "AWS", "PostgreSQL"],
    matchScore: 92,
    priorityScore: 95,
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com",
    postedAt: "2024-01-15T10:00:00Z",
    scrapedAt: "2024-01-15T12:00:00Z",
    skills: ["React", "TypeScript", "Node.js", "AWS", "PostgreSQL"],
    skillGaps: ["Kubernetes"],
  },
  {
    id: "2",
    title: "Full Stack Developer",
    company: "Meta",
    companyLogo: "https://logo.clearbit.com/meta.com",
    location: "Menlo Park, CA",
    type: "full-time",
    remote: "remote",
    salaryMin: 140000,
    salaryMax: 200000,
    salaryCurrency: "USD",
    description: "Join our team to build the next generation of social products.",
    requirements: ["3+ years of experience", "React", "Python", "GraphQL", "Docker"],
    niceToHave: ["React Native", "Hacklang"],
    techStack: ["React", "Python", "GraphQL", "Docker", "Redis"],
    matchScore: 88,
    priorityScore: 90,
    source: "Indeed",
    sourceUrl: "https://indeed.com",
    postedAt: "2024-01-14T09:00:00Z",
    scrapedAt: "2024-01-14T11:00:00Z",
    skills: ["React", "Python", "GraphQL", "Docker", "Redis"],
    skillGaps: ["Hacklang"],
  },
  {
    id: "3",
    title: "Backend Engineer",
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    location: "San Francisco, CA",
    type: "full-time",
    remote: "hybrid",
    salaryMin: 160000,
    salaryMax: 240000,
    salaryCurrency: "USD",
    description: "Build the infrastructure that powers the internet economy.",
    requirements: ["4+ years of experience", "Go", "Ruby", "PostgreSQL", "Distributed Systems"],
    niceToHave: ["Fintech experience", "API design"],
    techStack: ["Go", "Ruby", "PostgreSQL", "Redis", "Kubernetes"],
    matchScore: 85,
    priorityScore: 88,
    source: "Wellfound",
    sourceUrl: "https://wellfound.com",
    postedAt: "2024-01-13T14:00:00Z",
    scrapedAt: "2024-01-13T16:00:00Z",
    skills: ["Go", "Ruby", "PostgreSQL", "Distributed Systems"],
    skillGaps: [],
  },
  {
    id: "4",
    title: "Machine Learning Engineer",
    company: "OpenAI",
    companyLogo: "https://logo.clearbit.com/openai.com",
    location: "San Francisco, CA",
    type: "full-time",
    remote: "onsite",
    salaryMin: 180000,
    salaryMax: 300000,
    salaryCurrency: "USD",
    description: "Work on cutting-edge AI models and systems.",
    requirements: ["PhD or equivalent experience", "Python", "PyTorch", "TensorFlow", "ML Infrastructure"],
    niceToHave: ["Research publications", "Large language models"],
    techStack: ["Python", "PyTorch", "TensorFlow", "CUDA", "Kubernetes"],
    matchScore: 78,
    priorityScore: 95,
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com",
    postedAt: "2024-01-12T08:00:00Z",
    scrapedAt: "2024-01-12T10:00:00Z",
    skills: ["Python", "PyTorch", "TensorFlow", "ML Infrastructure"],
    skillGaps: ["PhD", "Research"],
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "Netflix",
    companyLogo: "https://logo.clearbit.com/netflix.com",
    location: "Los Gatos, CA",
    type: "full-time",
    remote: "remote",
    salaryMin: 130000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    description: "Build and maintain our cloud infrastructure.",
    requirements: ["4+ years of experience", "AWS", "Kubernetes", "Terraform", "CI/CD"],
    niceToHave: ["Chaos engineering", "Microservices"],
    techStack: ["AWS", "Kubernetes", "Terraform", "Jenkins", "Spinnaker"],
    matchScore: 82,
    priorityScore: 80,
    source: "Indeed",
    sourceUrl: "https://indeed.com",
    postedAt: "2024-01-11T11:00:00Z",
    scrapedAt: "2024-01-11T13:00:00Z",
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD"],
    skillGaps: [],
  },
];

export const sampleApplications: Application[] = [
  {
    id: "1",
    job: sampleJobs[0],
    status: "applied",
    resumeId: "1",
    resumeVersion: "v2.1",
    appliedAt: "2024-01-15T14:00:00Z",
    createdAt: "2024-01-15T14:00:00Z",
    updatedAt: "2024-01-15T14:00:00Z",
  },
  {
    id: "2",
    job: sampleJobs[1],
    status: "interview_scheduled",
    resumeId: "1",
    resumeVersion: "v2.1",
    appliedAt: "2024-01-10T10:00:00Z",
    viewedAt: "2024-01-11T09:00:00Z",
    interviewDate: "2024-01-20T15:00:00Z",
    interviewType: "video",
    recruiterName: "Sarah Johnson",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-12T10:00:00Z",
  },
  {
    id: "3",
    job: sampleJobs[2],
    status: "shortlisted",
    resumeId: "2",
    resumeVersion: "v1.5",
    appliedAt: "2024-01-08T11:00:00Z",
    viewedAt: "2024-01-09T08:00:00Z",
    createdAt: "2024-01-08T11:00:00Z",
    updatedAt: "2024-01-09T08:00:00Z",
  },
  {
    id: "4",
    job: sampleJobs[3],
    status: "rejected",
    resumeId: "1",
    resumeVersion: "v2.0",
    appliedAt: "2024-01-05T09:00:00Z",
    viewedAt: "2024-01-06T10:00:00Z",
    notes: "They went with a more senior candidate",
    createdAt: "2024-01-05T09:00:00Z",
    updatedAt: "2024-01-07T10:00:00Z",
  },
  {
    id: "5",
    job: sampleJobs[4],
    status: "queued",
    resumeId: "1",
    resumeVersion: "v2.1",
    createdAt: "2024-01-14T16:00:00Z",
    updatedAt: "2024-01-14T16:00:00Z",
  },
];

export const sampleResumes: Resume[] = [
  {
    id: "1",
    name: "Full Stack Developer Resume",
    targetRole: "Full Stack Developer",
    atsScore: 92,
    fileName: "resume_fullstack_v2.1.pdf",
    jobId: "1",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:00:00Z",
  },
  {
    id: "2",
    name: "Backend Engineer Resume",
    targetRole: "Backend Engineer",
    atsScore: 88,
    fileName: "resume_backend_v1.5.pdf",
    jobId: "2",
    createdAt: "2024-01-05T09:00:00Z",
    updatedAt: "2024-01-08T11:00:00Z",
  },
  {
    id: "3",
    name: "General Software Engineer",
    targetRole: "Software Engineer",
    atsScore: 85,
    fileName: "resume_general_v1.0.pdf",
    createdAt: "2023-12-01T10:00:00Z",
    updatedAt: "2023-12-01T10:00:00Z",
  },
];

export const sampleCoverLetters: CoverLetter[] = [
  {
    id: "1",
    company: "Google",
    role: "Senior Software Engineer",
    content: "Dear Hiring Manager,\n\nI am writing to express my strong interest...",
    jobId: "1",
    createdAt: "2024-01-15T13:00:00Z",
  },
  {
    id: "2",
    company: "Meta",
    role: "Full Stack Developer",
    content: "Dear Hiring Manager,\n\nI am excited to apply...",
    jobId: "2",
    createdAt: "2024-01-10T09:00:00Z",
  },
];

export const sampleInterviews: Interview[] = [
  {
    id: "1",
    applicationId: "2",
    company: "Meta",
    role: "Full Stack Developer",
    interviewDate: "2024-01-20T15:00:00Z",
    interviewType: "video",
    status: "scheduled",
    preparationPlan: [
      { id: "1", type: "company", title: "Meta Culture", content: "Focus on Move Fast and Build Things..." },
      { id: "2", type: "technical", title: "React Patterns", content: "Practice compound components, HOCs..." },
    ],
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-12T10:00:00Z",
  },
  {
    id: "2",
    applicationId: "3",
    company: "Stripe",
    role: "Backend Engineer",
    interviewDate: "2024-01-25T14:00:00Z",
    interviewType: "technical",
    status: "scheduled",
    preparationPlan: [
      { id: "1", type: "company", title: "Stripe Values", content: "Customer obsession, transparency..." },
    ],
    createdAt: "2024-01-09T08:00:00Z",
    updatedAt: "2024-01-09T08:00:00Z",
  },
];

export const sampleActivities: Activity[] = [
  {
    id: "1",
    type: "job_scraped",
    title: "New Job Found",
    description: "Found 5 new jobs matching your profile",
    timestamp: "2024-01-15T12:00:00Z",
  },
  {
    id: "2",
    type: "resume_generated",
    title: "Resume Generated",
    description: "Generated tailored resume for Google Senior Software Engineer",
    timestamp: "2024-01-15T11:30:00Z",
  },
  {
    id: "3",
    type: "application_submitted",
    title: "Application Submitted",
    description: "Applied to Google - Senior Software Engineer",
    timestamp: "2024-01-15T11:00:00Z",
  },
  {
    id: "4",
    type: "interview_scheduled",
    title: "Interview Scheduled",
    description: "Video interview scheduled with Meta for Jan 20th",
    timestamp: "2024-01-12T10:00:00Z",
  },
  {
    id: "5",
    type: "notification_sent",
    title: "Follow-up Sent",
    description: "Automated follow-up email sent to Stripe",
    timestamp: "2024-01-11T09:00:00Z",
  },
];

export const sampleAnalytics: Analytics = {
  totalApplications: 24,
  totalResponses: 8,
  totalInterviews: 3,
  totalOffers: 1,
  responseRate: 33.3,
  interviewRate: 12.5,
  offerRate: 4.2,
  applicationsPerWeek: [
    { week: "Week 1", count: 5 },
    { week: "Week 2", count: 7 },
    { week: "Week 3", count: 4 },
    { week: "Week 4", count: 8 },
  ],
  skillsDemand: [
    { skill: "React", count: 45 },
    { skill: "TypeScript", count: 38 },
    { skill: "Node.js", count: 32 },
    { skill: "Python", count: 28 },
    { skill: "AWS", count: 25 },
    { skill: "Go", count: 20 },
    { skill: "Kubernetes", count: 18 },
    { skill: "GraphQL", count: 15 },
  ],
};

export const sampleAgentLogs: AgentLog[] = [
  {
    id: "1",
    task: "Job Discovery",
    status: "completed",
    timestamp: "2024-01-15T12:00:00Z",
    duration: "2m 34s",
    details: "Found 5 new jobs",
  },
  {
    id: "2",
    task: "Resume Generation",
    status: "completed",
    timestamp: "2024-01-15T11:30:00Z",
    duration: "45s",
    details: "Generated resume for Google",
  },
  {
    id: "3",
    task: "Application Submission",
    status: "completed",
    timestamp: "2024-01-15T11:00:00Z",
    duration: "1m 12s",
    details: "Submitted application to Google",
  },
  {
    id: "4",
    task: "Follow-up Emails",
    status: "running",
    timestamp: "2024-01-15T10:00:00Z",
    details: "Sending follow-up emails...",
  },
  {
    id: "5",
    task: "Job Discovery",
    status: "failed",
    timestamp: "2024-01-14T12:00:00Z",
    duration: "30s",
    details: "LinkedIn rate limit reached",
  },
];
